name: Python-Test
on:
    push
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-python@v4
        - name: installing requirements
          run: pip install -r requirements.txt
        - name: running pytest
          run: pytest
    
    
