name: Python-Test
on:
    push
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 
        - uses: actions/setup-python@v4
          with: 
              python-version: ${{matrix.python-version}}
        - name: installing requirements
          run: pip install -r requirements.txt
        - name: running pytest
          run: pytest
    
    
