name: Schedule-task
on:
  
  schedule:
      - cron: "*/5 * * * *"
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: scheduled-print-msg
      run: |
        echo "Current date is:"
        date
        echo "Scheduled task complete"
